class Ipl
{
public static void main(String team[])
{
String rcbPlayer[]={"VK","ABD","siraj","patel","dk","maxwell","pattidar","villi","hasaranga","ahmed","Faf"};
System.out.println("playing rcbplayers 11 are:");
System.out.println(rcbPlayer[0]);
System.out.println(rcbPlayer[1]);
System.out.println(rcbPlayer[2]);
System.out.println(rcbPlayer[3]);
System.out.println(rcbPlayer[4]);
System.out.println(rcbPlayer[5]);
System.out.println(rcbPlayer[6]);
System.out.println(rcbPlayer[7]);
System.out.println(rcbPlayer[8]);
System.out.println(rcbPlayer[9]);
System.out.println(rcbPlayer[10]);
String cskPlayers[]={"MSD","devon","rutu","subhranshu","ambati","ajinkya","shaik","jadeja","dwaine","mitchell","ali"};
System.out.println("playing cskplayers 11 are:");
System.out.println(cskPlayers[0]);
System.out.println(cskPlayers[1]);
System.out.println(cskPlayers[2]);
System.out.println(cskPlayers[3]);
System.out.println(cskPlayers[4]);
System.out.println(cskPlayers[5]);
System.out.println(cskPlayers[6]);
System.out.println(cskPlayers[7]);
System.out.println(cskPlayers[8]);
System.out.println(cskPlayers[9]);
System.out.println(cskPlayers[10]);
String gtPlayers[]={"Pandya","gill","kane","rashid khan","david","joseph","darshan","jayant","pradeep","wade","abhinav"};
System.out.println("playing gtplayers 11 are:");
System.out.println(gtPlayers[0]);
System.out.println(gtPlayers[1]);
System.out.println(gtPlayers[2]);
System.out.println(gtPlayers[3]);
System.out.println(gtPlayers[4]);
System.out.println(gtPlayers[5]);
System.out.println(gtPlayers[6]);
System.out.println(gtPlayers[7]);
System.out.println(gtPlayers[8]);
System.out.println(gtPlayers[9]);
System.out.println(gtPlayers[10]);
String lsgPlayers[]={"kl Rahul","kyle","mark","ayush","de kock","pooran","krunal pandya","avesh khan","thakur","deepak","singh"};
System.out.println("playing lsgplayers 11 are:");
System.out.println(lsgPlayers[0]);
System.out.println(lsgPlayers[1]);
System.out.println(lsgPlayers[2]);
System.out.println(lsgPlayers[3]);
System.out.println(lsgPlayers[4]);
System.out.println(lsgPlayers[5]);
System.out.println(lsgPlayers[6]);
System.out.println(lsgPlayers[7]);
System.out.println(lsgPlayers[8]);
System.out.println(lsgPlayers[9]);
System.out.println(lsgPlayers[10]); 
String kkrPlayers[]={"iyer","rinku","shardul","gurbaz","andre russel","rana","venkatesh iyer","varun","umesh yadav","vaibhav","roy"};
System.out.println("playing kkrPlayers 11 are:");
System.out.println(kkrPlayers[0]);
System.out.println(kkrPlayers[1]);
System.out.println(kkrPlayers[2]);
System.out.println(kkrPlayers[3]);
System.out.println(kkrPlayers[4]);
System.out.println(kkrPlayers[5]);
System.out.println(kkrPlayers[6]);
System.out.println(kkrPlayers[7]);
System.out.println(kkrPlayers[8]);
System.out.println(kkrPlayers[9]);
System.out.println(kkrPlayers[10]);
String rrPlayers[]={"sanju","jos","devdutt","joe root","riyan parag","ashwin","jaiswal","krishna","hetmyer","holder","sharma"};
System.out.println("playing rrPlayers 11 are:");
System.out.println(rrPlayers[0]);
System.out.println(rrPlayers[1]);
System.out.println(rrPlayers[2]);
System.out.println(rrPlayers[3]);
System.out.println(rrPlayers[4]);
System.out.println(rrPlayers[5]);
System.out.println(rrPlayers[6]);
System.out.println(rrPlayers[7]);
System.out.println(rrPlayers[8]);
System.out.println(rrPlayers[9]);
System.out.println(rrPlayers[10]);
String srhPlayers[]={"umran malik","brook","agarwal","bhuvneshwar kumar","rahul","singh","natarajan","nitish","yadav","sharma","akeal"};
System.out.println("playing srhPlayers 11 are:");
System.out.println(srhPlayers[0]);
System.out.println(srhPlayers[1]);
System.out.println(srhPlayers[2]);
System.out.println(srhPlayers[3]);
System.out.println(srhPlayers[4]);
System.out.println(srhPlayers[5]);
System.out.println(srhPlayers[6]);
System.out.println(srhPlayers[7]);
System.out.println(srhPlayers[8]);
System.out.println(srhPlayers[9]);
System.out.println(srhPlayers[10]);
String pkPlayers[]={"dhawan","johny","sam","arshdeep","raza","rahul chahar","shahrukh khan","shivam","raj","mohit","rishi"};
System.out.println("playing pkPlayers 11 are:");
System.out.println(pkPlayers[0]);
System.out.println(pkPlayers[1]);
System.out.println(pkPlayers[2]);
System.out.println(pkPlayers[3]);
System.out.println(pkPlayers[4]);
System.out.println(pkPlayers[5]);
System.out.println(pkPlayers[6]);
System.out.println(pkPlayers[7]);
System.out.println(pkPlayers[8]);
System.out.println(pkPlayers[9]);
System.out.println(pkPlayers[10]);
String miPlayers[]={"rohit","suryakumar yadav","tim david","ishan kishan","bumrah","piyush","arjun","hrithik","tilak","trista","jhye"};
System.out.println("playing miPlayers 11 are:");
System.out.println(miPlayers[0]);
System.out.println(miPlayers[1]);
System.out.println(miPlayers[2]);
System.out.println(miPlayers[3]);
System.out.println(miPlayers[4]);
System.out.println(miPlayers[5]);
System.out.println(miPlayers[6]);
System.out.println(miPlayers[7]);
System.out.println(miPlayers[8]);
System.out.println(miPlayers[9]);
System.out.println(miPlayers[10]);
String dcPlayers[]={"Axar patel","lalit yadav","mitchell marsh","david warner","ripal patel","vicky ostwal","aman khan","pritvi","chetan","yash dhull","lungi ngidi"};
System.out.println("playing dcPlayers 11 are:");
System.out.println(dcPlayers[0]);
System.out.println(dcPlayers[1]);
System.out.println(dcPlayers[2]);
System.out.println(dcPlayers[3]);
System.out.println(dcPlayers[4]);
System.out.println(dcPlayers[5]);
System.out.println(dcPlayers[6]);
System.out.println(dcPlayers[7]);
System.out.println(dcPlayers[8]);
System.out.println(dcPlayers[9]);
System.out.println(dcPlayers[10]);
}
}